version: '3.9'
x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: 172.18.0.9:24224

services:
  explorer:
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    restart: on-failure
    networks:
      - database
      - monitoring
    ports:
      - "44333:80"
    environment:
      DATABASE_HOST: explorer_db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - explorer_db

  encounters:
    image: encounters-service
    restart: on-failure
    networks:
      - database
    ports:
      - "8087:8087"
    environment:
      DATABASE_HOST: explorer_db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - explorer_db

  followers:
    image: followers-service
    restart: on-failure
    container_name: "followers-server"
    #hostname: "followers-server"
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - NEO4J_DB=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASS=NekaSifra
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    logging: *fluent-bit
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - database
      - monitoring

  neo4j:
    image: neo4j
    restart: always
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo RETURN 1 | cypher-shell -a bolt://neo4j:7687 -u neo4j -p NekaSifra || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - NEO4J_AUTH=neo4j/NekaSifra
    volumes:
    - followers-data:/data
    - ./init-scripts:/docker-entrypoint-initdb.d # Mounting init-scripts directory
    networks:
    - monitoring
    
  tours: 
    image: tours-service
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      - MONGO_DB_URI=mongodb://root:pass@mongo:27017
    depends_on:
      mongo:
        condition: service_healthy

  explorer_db:
    image: postgres:latest
    restart: always
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: explorer
    volumes:
      - type: volume
        source: explorer-data
        target: /var/lib/postgresql/data
      - type: bind
        source: explorer-init-data.sql
        target: /tmp/explorer-init.sql
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db
    
  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - mongo_express_data:/data/db
  

volumes:
  explorer-data:
    name: explorer-data
  mongo_store:
  mongo_express_data:
  followers-data:

networks:
  database:
    driver: bridge
  monitoring:
    external:
      name: monitoring