global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "rules/recording_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['192.168.0.20:9182']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['cadvisor:8080'] 
